export { FunHoverText } from "./fun-text";
export { FunText } from "./fun-text";
export { GlitchText } from "./glitch-text";
export type { GradientColors } from "./gradient-text";
export { variations } from "./gradient-text";
export { GradientText } from "./gradient-text";
export { Heading2 } from "./heading";
export { AnimatedHeading } from "./heading";
export { TextFlipper } from "./text-flipper";
export { Underline } from "./underline";
export { HighlightText } from "./underline";
